<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/ads/googleads/v1/common/dates.proto

namespace GPBMetadata\Google\Ads\Googleads\V1\Common;

class Dates
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Google\Api\Annotations::initOnce();
        \GPBMetadata\Google\Protobuf\Wrappers::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0acb030a2a676f6f676c652f6164732f676f6f676c656164732f76312f63" .
            "6f6d6d6f6e2f64617465732e70726f746f121e676f6f676c652e6164732e" .
            "676f6f676c656164732e76312e636f6d6d6f6e1a1e676f6f676c652f7072" .
            "6f746f6275662f77726170706572732e70726f746f226d0a094461746552" .
            "616e676512300a0a73746172745f6461746518012001280b321c2e676f6f" .
            "676c652e70726f746f6275662e537472696e6756616c7565122e0a08656e" .
            "645f6461746518022001280b321c2e676f6f676c652e70726f746f627566" .
            "2e537472696e6756616c756542e5010a22636f6d2e676f6f676c652e6164" .
            "732e676f6f676c656164732e76312e636f6d6d6f6e420a44617465735072" .
            "6f746f50015a44676f6f676c652e676f6c616e672e6f72672f67656e7072" .
            "6f746f2f676f6f676c65617069732f6164732f676f6f676c656164732f76" .
            "312f636f6d6d6f6e3b636f6d6d6f6ea20203474141aa021e476f6f676c65" .
            "2e4164732e476f6f676c654164732e56312e436f6d6d6f6eca021e476f6f" .
            "676c655c4164735c476f6f676c654164735c56315c436f6d6d6f6eea0222" .
            "476f6f676c653a3a4164733a3a476f6f676c654164733a3a56313a3a436f" .
            "6d6d6f6e620670726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

