<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/ads/googleads/v1/common/explorer_auto_optimizer_setting.proto

namespace GPBMetadata\Google\Ads\Googleads\V1\Common;

class ExplorerAutoOptimizerSetting
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Google\Api\Annotations::initOnce();
        \GPBMetadata\Google\Protobuf\Wrappers::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0ad9030a44676f6f676c652f6164732f676f6f676c656164732f76312f63" .
            "6f6d6d6f6e2f6578706c6f7265725f6175746f5f6f7074696d697a65725f" .
            "73657474696e672e70726f746f121e676f6f676c652e6164732e676f6f67" .
            "6c656164732e76312e636f6d6d6f6e1a1e676f6f676c652f70726f746f62" .
            "75662f77726170706572732e70726f746f224a0a1c4578706c6f72657241" .
            "75746f4f7074696d697a657253657474696e67122a0a066f70745f696e18" .
            "012001280b321a2e676f6f676c652e70726f746f6275662e426f6f6c5661" .
            "6c756542fc010a22636f6d2e676f6f676c652e6164732e676f6f676c6561" .
            "64732e76312e636f6d6d6f6e42214578706c6f7265724175746f4f707469" .
            "6d697a657253657474696e6750726f746f50015a44676f6f676c652e676f" .
            "6c616e672e6f72672f67656e70726f746f2f676f6f676c65617069732f61" .
            "64732f676f6f676c656164732f76312f636f6d6d6f6e3b636f6d6d6f6ea2" .
            "0203474141aa021e476f6f676c652e4164732e476f6f676c654164732e56" .
            "312e436f6d6d6f6eca021e476f6f676c655c4164735c476f6f676c654164" .
            "735c56315c436f6d6d6f6eea0222476f6f676c653a3a4164733a3a476f6f" .
            "676c654164733a3a56313a3a436f6d6d6f6e620670726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

