<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/ads/googleads/v1/common/text_label.proto

namespace GPBMetadata\Google\Ads\Googleads\V1\Common;

class TextLabel
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Google\Api\Annotations::initOnce();
        \GPBMetadata\Google\Protobuf\Wrappers::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0add030a2f676f6f676c652f6164732f676f6f676c656164732f76312f63" .
            "6f6d6d6f6e2f746578745f6c6162656c2e70726f746f121e676f6f676c65" .
            "2e6164732e676f6f676c656164732e76312e636f6d6d6f6e1a1e676f6f67" .
            "6c652f70726f746f6275662f77726170706572732e70726f746f22760a09" .
            "546578744c6162656c12360a106261636b67726f756e645f636f6c6f7218" .
            "012001280b321c2e676f6f676c652e70726f746f6275662e537472696e67" .
            "56616c756512310a0b6465736372697074696f6e18022001280b321c2e67" .
            "6f6f676c652e70726f746f6275662e537472696e6756616c756542e9010a" .
            "22636f6d2e676f6f676c652e6164732e676f6f676c656164732e76312e63" .
            "6f6d6d6f6e420e546578744c6162656c50726f746f50015a44676f6f676c" .
            "652e676f6c616e672e6f72672f67656e70726f746f2f676f6f676c656170" .
            "69732f6164732f676f6f676c656164732f76312f636f6d6d6f6e3b636f6d" .
            "6d6f6ea20203474141aa021e476f6f676c652e4164732e476f6f676c6541" .
            "64732e56312e436f6d6d6f6eca021e476f6f676c655c4164735c476f6f67" .
            "6c654164735c56315c436f6d6d6f6eea0222476f6f676c653a3a4164733a" .
            "3a476f6f676c654164733a3a56313a3a436f6d6d6f6e620670726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

