<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/ads/googleads/v1/common/url_collection.proto

namespace GPBMetadata\Google\Ads\Googleads\V1\Common;

class UrlCollection
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Google\Api\Annotations::initOnce();
        \GPBMetadata\Google\Protobuf\Wrappers::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0ae0040a33676f6f676c652f6164732f676f6f676c656164732f76312f63" .
            "6f6d6d6f6e2f75726c5f636f6c6c656374696f6e2e70726f746f121e676f" .
            "6f676c652e6164732e676f6f676c656164732e76312e636f6d6d6f6e1a1e" .
            "676f6f676c652f70726f746f6275662f77726170706572732e70726f746f" .
            "22f0010a0d55726c436f6c6c656374696f6e12370a1175726c5f636f6c6c" .
            "656374696f6e5f696418012001280b321c2e676f6f676c652e70726f746f" .
            "6275662e537472696e6756616c756512300a0a66696e616c5f75726c7318" .
            "022003280b321c2e676f6f676c652e70726f746f6275662e537472696e67" .
            "56616c756512370a1166696e616c5f6d6f62696c655f75726c7318032003" .
            "280b321c2e676f6f676c652e70726f746f6275662e537472696e6756616c" .
            "7565123b0a15747261636b696e675f75726c5f74656d706c617465180420" .
            "01280b321c2e676f6f676c652e70726f746f6275662e537472696e675661" .
            "6c756542ed010a22636f6d2e676f6f676c652e6164732e676f6f676c6561" .
            "64732e76312e636f6d6d6f6e421255726c436f6c6c656374696f6e50726f" .
            "746f50015a44676f6f676c652e676f6c616e672e6f72672f67656e70726f" .
            "746f2f676f6f676c65617069732f6164732f676f6f676c656164732f7631" .
            "2f636f6d6d6f6e3b636f6d6d6f6ea20203474141aa021e476f6f676c652e" .
            "4164732e476f6f676c654164732e56312e436f6d6d6f6eca021e476f6f67" .
            "6c655c4164735c476f6f676c654164735c56315c436f6d6d6f6eea022247" .
            "6f6f676c653a3a4164733a3a476f6f676c654164733a3a56313a3a436f6d" .
            "6d6f6e620670726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

