<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/ads/googleads/v1/resources/ad_group_label.proto

namespace GPBMetadata\Google\Ads\Googleads\V1\Resources;

class AdGroupLabel
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Google\Api\Annotations::initOnce();
        \GPBMetadata\Google\Protobuf\Wrappers::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0a89040a36676f6f676c652f6164732f676f6f676c656164732f76312f72" .
            "65736f75726365732f61645f67726f75705f6c6162656c2e70726f746f12" .
            "21676f6f676c652e6164732e676f6f676c656164732e76312e7265736f75" .
            "726365731a1e676f6f676c652f70726f746f6275662f7772617070657273" .
            "2e70726f746f2282010a0c416447726f75704c6162656c12150a0d726573" .
            "6f757263655f6e616d65180120012809122e0a0861645f67726f75701802" .
            "2001280b321c2e676f6f676c652e70726f746f6275662e537472696e6756" .
            "616c7565122b0a056c6162656c18032001280b321c2e676f6f676c652e70" .
            "726f746f6275662e537472696e6756616c756542fe010a25636f6d2e676f" .
            "6f676c652e6164732e676f6f676c656164732e76312e7265736f75726365" .
            "734211416447726f75704c6162656c50726f746f50015a4a676f6f676c65" .
            "2e676f6c616e672e6f72672f67656e70726f746f2f676f6f676c65617069" .
            "732f6164732f676f6f676c656164732f76312f7265736f75726365733b72" .
            "65736f7572636573a20203474141aa0221476f6f676c652e4164732e476f" .
            "6f676c654164732e56312e5265736f7572636573ca0221476f6f676c655c" .
            "4164735c476f6f676c654164735c56315c5265736f7572636573ea022547" .
            "6f6f676c653a3a4164733a3a476f6f676c654164733a3a56313a3a526573" .
            "6f7572636573620670726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

