<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/ads/googleads/v1/resources/ad_group_criterion_label.proto

namespace GPBMetadata\Google\Ads\Googleads\V1\Resources;

class AdGroupCriterionLabel
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Google\Api\Annotations::initOnce();
        \GPBMetadata\Google\Protobuf\Wrappers::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0aaf040a40676f6f676c652f6164732f676f6f676c656164732f76312f72" .
            "65736f75726365732f61645f67726f75705f637269746572696f6e5f6c61" .
            "62656c2e70726f746f1221676f6f676c652e6164732e676f6f676c656164" .
            "732e76312e7265736f75726365731a1e676f6f676c652f70726f746f6275" .
            "662f77726170706572732e70726f746f2295010a15416447726f75704372" .
            "69746572696f6e4c6162656c12150a0d7265736f757263655f6e616d6518" .
            "012001280912380a1261645f67726f75705f637269746572696f6e180220" .
            "01280b321c2e676f6f676c652e70726f746f6275662e537472696e675661" .
            "6c7565122b0a056c6162656c18032001280b321c2e676f6f676c652e7072" .
            "6f746f6275662e537472696e6756616c75654287020a25636f6d2e676f6f" .
            "676c652e6164732e676f6f676c656164732e76312e7265736f7572636573" .
            "421a416447726f7570437269746572696f6e4c6162656c50726f746f5001" .
            "5a4a676f6f676c652e676f6c616e672e6f72672f67656e70726f746f2f67" .
            "6f6f676c65617069732f6164732f676f6f676c656164732f76312f726573" .
            "6f75726365733b7265736f7572636573a20203474141aa0221476f6f676c" .
            "652e4164732e476f6f676c654164732e56312e5265736f7572636573ca02" .
            "21476f6f676c655c4164735c476f6f676c654164735c56315c5265736f75" .
            "72636573ea0225476f6f676c653a3a4164733a3a476f6f676c654164733a" .
            "3a56313a3a5265736f7572636573620670726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

