<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/ads/googleads/v1/resources/customer_client.proto

namespace GPBMetadata\Google\Ads\Googleads\V1\Resources;

class CustomerClient
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Google\Api\Annotations::initOnce();
        \GPBMetadata\Google\Protobuf\Wrappers::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0ac0040a37676f6f676c652f6164732f676f6f676c656164732f76312f72" .
            "65736f75726365732f637573746f6d65725f636c69656e742e70726f746f" .
            "1221676f6f676c652e6164732e676f6f676c656164732e76312e7265736f" .
            "75726365731a1e676f6f676c652f70726f746f6275662f77726170706572" .
            "732e70726f746f22b6010a0e437573746f6d6572436c69656e7412150a0d" .
            "7265736f757263655f6e616d6518012001280912350a0f636c69656e745f" .
            "637573746f6d657218032001280b321c2e676f6f676c652e70726f746f62" .
            "75662e537472696e6756616c7565122a0a0668696464656e18042001280b" .
            "321a2e676f6f676c652e70726f746f6275662e426f6f6c56616c7565122a" .
            "0a056c6576656c18052001280b321b2e676f6f676c652e70726f746f6275" .
            "662e496e74363456616c75654280020a25636f6d2e676f6f676c652e6164" .
            "732e676f6f676c656164732e76312e7265736f7572636573421343757374" .
            "6f6d6572436c69656e7450726f746f50015a4a676f6f676c652e676f6c61" .
            "6e672e6f72672f67656e70726f746f2f676f6f676c65617069732f616473" .
            "2f676f6f676c656164732f76312f7265736f75726365733b7265736f7572" .
            "636573a20203474141aa0221476f6f676c652e4164732e476f6f676c6541" .
            "64732e56312e5265736f7572636573ca0221476f6f676c655c4164735c47" .
            "6f6f676c654164735c56315c5265736f7572636573ea0225476f6f676c65" .
            "3a3a4164733a3a476f6f676c654164733a3a56313a3a5265736f75726365" .
            "73620670726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

