<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/ads/googleads/v1/resources/landing_page_view.proto

namespace GPBMetadata\Google\Ads\Googleads\V1\Resources;

class LandingPageView
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Google\Api\Annotations::initOnce();
        \GPBMetadata\Google\Protobuf\Wrappers::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0af0030a39676f6f676c652f6164732f676f6f676c656164732f76312f72" .
            "65736f75726365732f6c616e64696e675f706167655f766965772e70726f" .
            "746f1221676f6f676c652e6164732e676f6f676c656164732e76312e7265" .
            "736f75726365731a1e676f6f676c652f70726f746f6275662f7772617070" .
            "6572732e70726f746f22640a0f4c616e64696e6750616765566965771215" .
            "0a0d7265736f757263655f6e616d65180120012809123a0a14756e657870" .
            "616e6465645f66696e616c5f75726c18022001280b321c2e676f6f676c65" .
            "2e70726f746f6275662e537472696e6756616c75654281020a25636f6d2e" .
            "676f6f676c652e6164732e676f6f676c656164732e76312e7265736f7572" .
            "63657342144c616e64696e67506167655669657750726f746f50015a4a67" .
            "6f6f676c652e676f6c616e672e6f72672f67656e70726f746f2f676f6f67" .
            "6c65617069732f6164732f676f6f676c656164732f76312f7265736f7572" .
            "6365733b7265736f7572636573a20203474141aa0221476f6f676c652e41" .
            "64732e476f6f676c654164732e56312e5265736f7572636573ca0221476f" .
            "6f676c655c4164735c476f6f676c654164735c56315c5265736f75726365" .
            "73ea0225476f6f676c653a3a4164733a3a476f6f676c654164733a3a5631" .
            "3a3a5265736f7572636573620670726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

