<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/ads/googleads/v1/resources/paid_organic_search_term_view.proto

namespace GPBMetadata\Google\Ads\Googleads\V1\Resources;

class PaidOrganicSearchTermView
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Google\Api\Annotations::initOnce();
        \GPBMetadata\Google\Protobuf\Wrappers::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0a87040a45676f6f676c652f6164732f676f6f676c656164732f76312f72" .
            "65736f75726365732f706169645f6f7267616e69635f7365617263685f74" .
            "65726d5f766965772e70726f746f1221676f6f676c652e6164732e676f6f" .
            "676c656164732e76312e7265736f75726365731a1e676f6f676c652f7072" .
            "6f746f6275662f77726170706572732e70726f746f22650a19506169644f" .
            "7267616e69635365617263685465726d5669657712150a0d7265736f7572" .
            "63655f6e616d6518012001280912310a0b7365617263685f7465726d1802" .
            "2001280b321c2e676f6f676c652e70726f746f6275662e537472696e6756" .
            "616c7565428b020a25636f6d2e676f6f676c652e6164732e676f6f676c65" .
            "6164732e76312e7265736f7572636573421e506169644f7267616e696353" .
            "65617263685465726d5669657750726f746f50015a4a676f6f676c652e67" .
            "6f6c616e672e6f72672f67656e70726f746f2f676f6f676c65617069732f" .
            "6164732f676f6f676c656164732f76312f7265736f75726365733b726573" .
            "6f7572636573a20203474141aa0221476f6f676c652e4164732e476f6f67" .
            "6c654164732e56312e5265736f7572636573ca0221476f6f676c655c4164" .
            "735c476f6f676c654164735c56315c5265736f7572636573ea0225476f6f" .
            "676c653a3a4164733a3a476f6f676c654164733a3a56313a3a5265736f75" .
            "72636573620670726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

