<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/ads/googleads/v1/resources/topic_constant.proto

namespace GPBMetadata\Google\Ads\Googleads\V1\Resources;

class TopicConstant
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Google\Api\Annotations::initOnce();
        \GPBMetadata\Google\Protobuf\Wrappers::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0ac0040a36676f6f676c652f6164732f676f6f676c656164732f76312f72" .
            "65736f75726365732f746f7069635f636f6e7374616e742e70726f746f12" .
            "21676f6f676c652e6164732e676f6f676c656164732e76312e7265736f75" .
            "726365731a1e676f6f676c652f70726f746f6275662f7772617070657273" .
            "2e70726f746f22b8010a0d546f706963436f6e7374616e7412150a0d7265" .
            "736f757263655f6e616d6518012001280912270a02696418022001280b32" .
            "1b2e676f6f676c652e70726f746f6275662e496e74363456616c7565123b" .
            "0a15746f7069635f636f6e7374616e745f706172656e7418032001280b32" .
            "1c2e676f6f676c652e70726f746f6275662e537472696e6756616c756512" .
            "2a0a047061746818042003280b321c2e676f6f676c652e70726f746f6275" .
            "662e537472696e6756616c756542ff010a25636f6d2e676f6f676c652e61" .
            "64732e676f6f676c656164732e76312e7265736f75726365734212546f70" .
            "6963436f6e7374616e7450726f746f50015a4a676f6f676c652e676f6c61" .
            "6e672e6f72672f67656e70726f746f2f676f6f676c65617069732f616473" .
            "2f676f6f676c656164732f76312f7265736f75726365733b7265736f7572" .
            "636573a20203474141aa0221476f6f676c652e4164732e476f6f676c6541" .
            "64732e56312e5265736f7572636573ca0221476f6f676c655c4164735c47" .
            "6f6f676c654164735c56315c5265736f7572636573ea0225476f6f676c65" .
            "3a3a4164733a3a476f6f676c654164733a3a56313a3a5265736f75726365" .
            "73620670726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

