<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/ads/googleads/v1/resources/video.proto

namespace GPBMetadata\Google\Ads\Googleads\V1\Resources;

class Video
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Google\Api\Annotations::initOnce();
        \GPBMetadata\Google\Protobuf\Wrappers::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0ad4040a2d676f6f676c652f6164732f676f6f676c656164732f76312f72" .
            "65736f75726365732f766964656f2e70726f746f1221676f6f676c652e61" .
            "64732e676f6f676c656164732e76312e7265736f75726365731a1e676f6f" .
            "676c652f70726f746f6275662f77726170706572732e70726f746f22dd01" .
            "0a05566964656f12150a0d7265736f757263655f6e616d65180120012809" .
            "12280a02696418022001280b321c2e676f6f676c652e70726f746f627566" .
            "2e537472696e6756616c756512300a0a6368616e6e656c5f696418032001" .
            "280b321c2e676f6f676c652e70726f746f6275662e537472696e6756616c" .
            "756512340a0f6475726174696f6e5f6d696c6c697318042001280b321b2e" .
            "676f6f676c652e70726f746f6275662e496e74363456616c7565122b0a05" .
            "7469746c6518052001280b321c2e676f6f676c652e70726f746f6275662e" .
            "537472696e6756616c756542f7010a25636f6d2e676f6f676c652e616473" .
            "2e676f6f676c656164732e76312e7265736f7572636573420a566964656f" .
            "50726f746f50015a4a676f6f676c652e676f6c616e672e6f72672f67656e" .
            "70726f746f2f676f6f676c65617069732f6164732f676f6f676c65616473" .
            "2f76312f7265736f75726365733b7265736f7572636573a20203474141aa" .
            "0221476f6f676c652e4164732e476f6f676c654164732e56312e5265736f" .
            "7572636573ca0221476f6f676c655c4164735c476f6f676c654164735c56" .
            "315c5265736f7572636573ea0225476f6f676c653a3a4164733a3a476f6f" .
            "676c654164733a3a56313a3a5265736f7572636573620670726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

